### PR TITLE
grails-melody-plugin issue 43

### PR DESCRIPTION
**Pull request by jukin-jerry**
Apply fix proposed by graemerocher in grails-core-10715: not a grails-core bug but instead in the plugin; https://github.com/grails/grails-core/issues/10715#issuecomment-317304931

### CODE REVIEW

**Comment by evernat** [comment]
This pull request si too short.
Have you tested it? Are services still monitored? Why was this call needed before Grails 3 and why it is not needed anymore?
Why writing `grailsVersion=3.2.11` in gradle.properties fixes the issue without this PR?

**Comment by bassmartin** [comment]
Applying this fix makes one of my test work (that was not working without the change) that modifies the metaclass of a domain class and uses @ConfineMetaClassChanges annotation.

I'll create a project that reproduces this.

I will now check that the plugin still monitor service with that change.

**Comment by bassmartin** [comment]
I still get stats about services in my project.

**Comment by sergiomichels** [comment]
@evernat I've checked that we have this `ExpandoMetaClass.enableGlobally()` since the SVN version of the plugin, so it's probably linked with an old version of Groovy... Since Martin tested it I think we can merge it.

**Comment by bassmartin** [comment]
We can safely remove the call as it's for older Groovy versions : https://stackoverflow.com/questions/34447528/what-are-the-costs-of-using-expandometaclass-enableglobally-groovy

**Comment by evernat** [comment]
Since the services are still monitored and give stats, it's ok to me.

**Pull request merged**
