### PR TITLE
Upgrade to Java Melody 1.71.0

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sergiomichels** [comment]
I'll leave this open a little more to remember of doing this release :)

**Comment by evernat** [comment]
javamelody-core 1.72.0 is just released, so you can bump to 1.72.0 instead of 1.71.0.

**Comment by evernat** [comment]
... or in a few hours when maven central is synced

**Comment by sergiomichels** [comment]
1.72.0 released

**Pull request closed without merging**
