### PR TITLE
Upgrade to Grails 3.x

### PR DESCRIPTION
**Pull request by sergiomichels**
This is the initial version of the plugin for Grails 3.x

### CODE REVIEW

**Comment by evernat** [comment]
Hi Sergio,
This looks good as far as I can tell.
First, how to release the plugin after that? Something like gradlew release?

A few remarks:
- javamelody dependency should be upgraded to 1.59.0.
- GitHub says "This branch has conflicts that must be resolved" so the "Merge pull request" button is disabled, perhaps because of "1.59.0" recent commits?
- I am not sure that a 2.0-SNAPSHOT version is for the better, because perhaps this plugin could continue to have versions synchronized with javamelody and with the Jenkins, Atlassian, Liferay and Sonar plugins.
- I suggest that you add your name in the plugin class next to Liu Chao and me.
- And by the way, you could become a commiter in this grails melody repository if I figure how to do that.

What do you think?

**Comment by sergiomichels** [comment]
Hi evernat, I missed your input, sorry. I will try to check your list today. 

I think if you add me as contributor of the repository I will be able to commit.

**Comment by evernat** [comment]
done, you are a contributor

**Comment by bassmartin** [comment]
I'm happy to see that you guys are working on that. @sergiomichels is you implementation based on the Spring Boot integration : https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#spring-boot-app ?

**Comment by sergiomichels** [comment]
@bassmartin In some way is similar, check my configuration: https://github.com/sergiomichels/grails-melody-plugin/blob/master/src/main/groovy/grails/melody/plugin/MelodyConfig.groovy

**Comment by evernat** [comment]
Thanks Sergio!
I have added 2 notes in the [Release Notes](https://github.com/javamelody/javamelody/wiki/ReleaseNotes):
  * In the JavaMelody Grails plugin, migrate the plugin to Grails 3.x and upload it to Bintray ([grails PR 33](https://github.com/javamelody/grails-melody-plugin/pull/33), thanks to _Sergio Michels_). The plugin is available in Bintray [here](https://bintray.com/grails/plugins?filterByPkgName=grails-melody-plugin).
  * [Sergio Michels](https://github.com/sergiomichels) is now committer in the [JavaMelody Grails plugin](https://github.com/javamelody/grails-melody-plugin).

Can I announce that in the [users' group](https://groups.google.com/forum/#!forum/javamelody) ?

**Comment by sergiomichels** [comment]
Yes, I've already made a test and it is available in the Grails plugins repository.

**Comment by evernat** [comment]
Hi Sergio,
Here is the mail I have sent to the users' group:
https://groups.google.com/forum/#!topic/javamelody/rABw7IY92UU

**Comment by sergiomichels** [comment]
Awesome!

**Pull request merged**
