### PR TITLE
Removing views that cause collision with other plugins/app.  Bumping …

### PR DESCRIPTION
**Pull request by ctoestreich**
…version.

Addressing issue #35

### CODE REVIEW

**Comment by ctoestreich** [comment]
@sergiomichels release?

**Comment by sergiomichels** [comment]
@evernat Should we replace the current version or create a new one? It will be not in sync with the Melody Java version...

**Comment by evernat** [comment]
I think that we should not replace versions once released.
So, it is possible to release a new version of the grails one. The new one should certainly be 1.60.1. The minor digit at the end is here for patchs like that.

**Comment by sergiomichels** [comment]
@ctoestreich done...

**Pull request merged**
